src/Entity/News.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsRepository")
 */
class News
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $img;

    /**
     * @return mixed
     */
    public function getImg()
    {
        return $this->img;
    }

    /**
     * @param mixed $img
     */
    public function setImg($img): void
    {
        $this->img = $img;
    }

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $data
     */
    public function setDate($date): void
    {
        $this->date = $date;
    }



    /**
     * @ORM\Column(type="string", length=130, unique=true)
     */
    private $slug;

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     */
    public function setSlug($slug): void
    {
        $this->slug = $slug;
    }

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }
}

src/Entity/NewsComment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NewsCommentRepository")
 */
class NewsComment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=110)
     */
    private $news_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $time;

    /**
     * @return mixed
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * @param mixed $time
     */
    public function setTime($time): void
    {
        $this->time = $time;
    }

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $user_name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNewsName(): ?string
    {
        return $this->news_name;
    }

    public function setNewsName(string $news_name): self
    {
        $this->news_name = $news_name;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }
}

src/Entity/Seo.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SeoRepository")
 */
class Seo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $news_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $html_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $alt;

    /**
     * @return mixed
     */
    public function getNewsName()
    {
        return $this->news_name;
    }

    /**
     * @param mixed $news_name
     */
    public function setNewsName($news_name): void
    {
        $this->news_name = $news_name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHtmlTitle(): ?string
    {
        return $this->html_title;
    }

    public function setHtmlTitle(string $html_title): self
    {
        $this->html_title = $html_title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAlt(): ?string
    {
        return $this->alt;
    }

    public function setAlt(?string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }
}

src/Controller/NewsController.php
<?php

namespace App\Controller;

use App\Entity\News;
use App\Entity\NewsComment;
use App\Entity\Seo;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class NewsController extends AbstractController
{

    /**
     * @Route("/news-{page<\d+>}", name="news")
     */
    public function index($page)
    {
        $em = $this->getDoctrine()->getManager()->getRepository(News::class);

        $pageData = $em->getByPage($page);


        return $this->render('news/index.html.twig', [
            'page' => $page,
            'last_page' => ceil($em->getTableCount() / 9),
            'content' => $pageData
        ]);
    }

    /**
     * @Route("/news/{slug}", name="slug")
     */
    public function single($slug, Request $request)
    {
        if ($request->request->count() != 0) { //блок отвечает за добавления комментария в базу

            if ($request->request->get('g-recaptcha-response'))
            {
                $url = 'https://www.google.com/recaptcha/api/siteverify?';

                $query = http_build_query([

                    'secret' => '6LfBGLEUAAAAALn6qFzJy8saIK7wsAId7uldcrW3',
                    'response' => $request->request->get('g-recaptcha-response'),
                    'remoteip' => $request->getClientIp()
                ]);

               $recaptchaData =  json_decode(file_get_contents($url . $query), true);

               if($recaptchaData['success'])
               {
                   $dbComment = new NewsComment();

                   $dbComment->setComment($request->request->get('msg'));
                   $dbComment->setNewsName($slug);
                   $dbComment->setTime(time());
                   $dbComment->setUserName($request->request->get('name'));

                   $this->getDoctrine()->getManager()->persist($dbComment);
                   $this->getDoctrine()->getManager()->flush();

               }

            }



        }

        $emNews = $this->getDoctrine()->getManager()->getRepository(News::class);
        $emNewsComment = $this->getDoctrine()->getManager()->getRepository(NewsComment::class);
        $emSeo = $this->getDoctrine()->getManager()->getRepository(Seo::class);

        $content = $emNews->findOneBy(['slug' => $slug]);

        if ($content == null) //проверка на существование записи в бд
            throw $this->createNotFoundException('Not found 404');

        $comment = $emNewsComment->findBy(['news_name' => $slug],['id' => 'DESC']);
        $seo = $emSeo->findOneBy(['news_name' => $slug]);

        return $this->render('news/single-blog.html.twig', [
            'content' => $content,
            'random_content' => $emNews->getRandom(4),
            'comment' => $comment,
            'seo' => $seo
        ]);
    }
}

templates/news/index.html.twig
{% include 'usual_template/header.html.twig' %}

<title>Новости киберспорта. CS, DOTA, Starcraft.</title>

<meta name="description" content="Последние новости из мира киберспорта. Результаты событий, прогнозы и актуальная информация из мира киберспорта.">

<!-- preloader start -->
<div id="preloader"></div>
<!-- preloader end -->

<div class="custom-cursor"></div>
<!--  header-section start  -->
<header class="header-section">
    <div class="header-bottom">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <a class="site-logo site-title" href="/">Cyberrating.</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="menu-toggle"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav main-menu ml-auto">
                        <li ><a href="{{ path('mainpage') }}">Главная</a></li>
                        <li  ><a href="{{ path('bookmakerlist') }}">Букмекеры</a></li>
                        <li class="active menu_has_children"><a href="#">Новости/прогнозы</a>
                            <ul class="sub-menu">
                                <li ><a href="{{ path('news', {'page': 1}) }}">Новости</a></li>
                                <li><a href="{{ path('forecast') }}">Прогнозы</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ path('bonus') }}">Бонусы</a></li>
                        <li class="menu_has_children"><a href="#">Матчи/Коэффициенты</a>
                            <ul class="sub-menu">
                                <li ><a href="{{ path('match_result') }}">Результаты матчей</a></li>
                                <li ><a href="{{ path('coef') }}">Коэффициенты</a></li>
                            </ul>
                        </li>
                        <li class="menu_has_children"><a href="#">Информация</a>
                            <ul class="sub-menu">
                                <li><a href="{{ path('contact') }}">Контакты</a></li>
                                <li><a href="{{ path('policy') }}">Политика</a></li>
                                <!-- <li><a href="service.html">Services</a></li>
                                <li><a href="login.html">Login</a></li>
                                <li><a href="registration.html">Registration</a></li>
                                <li><a href="faq.html">FAQ</a></li>
                                <li><a href="error-404.html">ERROR Page</a></li> -->
                            </ul>
                        </li>
                        <li><a href="{{ path('about') }}">О нас</a></li>

                    </ul>
                </div>
            </nav>
        </div>
    </div><!-- header-bottom end -->
</header>
<!--  header-section end  -->

<!-- banner-section start -->
<section class="breadcum-section">
    <div class="breadcum-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcum-content text-center">
                        <h3 class="title">Новости</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Домой</a></li>
                            <li class="breadcrumb-item active">Новости</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- banner-section end -->

<!-- blog-section start -->
<section class="blog-section section-padding">
    <div class="container">
        <div class="row mt-mb-15">

            {% for i in 0..content|length-1 %}
            <div class="col-lg-4 col-sm-6">
                <div class="post-item">
                    <div class="thumb">
                        <a href="news/{{ content[i].slug}}">

                            <img style="height: 28vh;" src="{{ content[i].img}}" alt="{{ content[i].title}}">

                        </a>
                    </div>
                    <div class="content">
                        <ul class="post-meta">
                            <li><a href="news/{{ content[i].slug}}"><i class="fa fa-calendar"></i>{{ content[i].date|date("d/M/Y") }}</a></li>
                        </ul>
                        <h5 class="post-title"><a href="news/{{ content[i].slug}}">{{ content[i].title }}</a></h5>
                        <p>{{ content[i].text|slice(0,95) }}...</p>
                    </div>
                </div>
            </div><!-- post-item end -->

            {% endfor %}
        </div>
        <div class="row">
            <div class="col-lg-12">
                <nav class="d-pagination" aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">

                        {% if page == 1 %}
                        <li class="page-item disabled  ">
                            <a class="page-link" href="news-{{ page-1 }}"><</a></li>

                        {% else %}

                            <li class="page-item   ">
                                <a class="page-link" href="news-{{ page-1 }}"><</a></li>
                            <li class="page-item">
                                <a class="page-link" href="news-{{ page-1 }}">{{ page - 1 }}</a></li>

                        {% endif %}


                        <li class="page-item active"><a class="page-link" >{{ page }}</a></li>


                        {% if page == last_page %}

                        <li class="page-item disabled"><a class="page-link" href="news-{{ page+1 }}">></a></li>

                        {% else %}

                        <li class="page-item "><a href="news-{{ page + 1 }}" class="page-link" >{{ page + 1 }}</a></li>
                            <li class="page-item "><a class="page-link" href="news-{{ page + 1 }}">></a></li>

                        {% endif %}



                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
<!-- blog-section end -->
{% include 'usual_template/footer.html.twig' %}

templates/news/single-blog.html.twig
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/png" href="{{ asset('assets/images/favicon.png') }}"/>
    <title>{{ seo.htmlTitle }}</title>
    <!-- fontawesome css link -->
    <link rel="stylesheet" href="{{ asset('assets/css/fontawesome.min.css') }}">
    <!-- flat icon css link -->
    <link rel="stylesheet" href="{{ asset('assets/css/flaticon.css') }}">
    <!-- bootstrap css link -->
    <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
    <!-- animate css link -->
    <link rel="stylesheet" href="{{ asset('assets/css/animate.css') }}">
    <!-- slick slider css link -->
    <link rel="stylesheet" href="{{ asset('assets/css/slick.css') }}">
    <!-- lightcase css link -->
    <link rel="stylesheet" href="{{ asset('assets/css/lightcase.css') }}">
    <!-- main style css link -->
    <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
    <!-- responsive css file -->
    <link rel="stylesheet" href="{{ asset('assets/css/responsive.css') }}">
    <!-- google recaptcha js file -->
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
{#SEO#}

<meta name="description" content="{{ seo.description }}">
<!-- preloader start -->
<div id="preloader"></div>
<!-- preloader end -->

<div class="custom-cursor"></div>
<!--  header-section start  -->
<header class="header-section">
    <div class="header-bottom">
        <div class="container">
            <nav class="navbar navbar-expand-lg">
                <a class="site-logo site-title" href="/">Cyberrating.</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="menu-toggle"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav main-menu ml-auto">
                        <li ><a href="{{ path('mainpage') }}">Главная</a></li>
                        <li  ><a href="{{ path('bookmakerlist') }}">Букмекеры</a></li>
                        <li class="active menu_has_children"><a href="#">Новости/прогнозы</a>
                            <ul class="sub-menu">
                                <li ><a href="{{ path('news', {'page': 1}) }}">Новости</a></li>
                                <li><a href="{{ path('forecast') }}">Прогнозы</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ path('bonus') }}">Бонусы</a></li>
                        <li class="menu_has_children"><a href="#">Матчи/Коэффициенты</a>
                            <ul class="sub-menu">
                                <li ><a href="{{ path('match_result') }}">Результаты матчей</a></li>
                                <li ><a href="{{ path('coef') }}">Коэффициенты</a></li>
                            </ul>
                        </li>
                        <li class="menu_has_children"><a href="#">Информация</a>
                            <ul class="sub-menu">
                                <li><a href="{{ path('contact') }}">Контакты</a></li>
                                <li><a href="{{ path('policy') }}">Политика</a></li>
                                <!-- <li><a href="service.html">Services</a></li>
                                <li><a href="login.html">Login</a></li>
                                <li><a href="registration.html">Registration</a></li>
                                <li><a href="faq.html">FAQ</a></li>
                                <li><a href="error-404.html">ERROR Page</a></li> -->
                            </ul>
                        </li>
                        <li><a href="{{ path('about') }}">О нас</a></li>

                    </ul>
                </div>
            </nav>
        </div>
    </div><!-- header-bottom end -->
</header>
<!--  header-section end  -->

<!-- banner-section start -->
<section class="breadcum-section">
    <div class="breadcum-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcum-content text-center">
                        <h3 class="title">Новости</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Домой</a></li>
                            <li class="breadcrumb-item active">{{ content.title }}</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- banner-section end -->

<!-- blog-details-section start -->
<section class="blog-details-section section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog-details-wrapper">
                    <div class="blog-details-thumb">
                        <img src="{{ asset(content.img) }}" alt="image">
                    </div>
                    <div class="blog-details-content">
                        <ul class="post-meta">
                            <li><a href="blog-details.html#"><i class="fa fa-user"></i>{{ content.date|date("d/M/Y") }}</a></li>
                        </ul>
                        <h2 class="blog-details-title">{{ content.title }}</h2>
                       <p>{{ content.text|nl2br }}</p>
                    </div>

                    <div class="comment-form-wrap">
                        <h3 class="title">Оставить отзыв</h3>
                        <form class="cmn-form comment-form" action="" method="post">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="frm-group">
                                        <input type="text" name="name" id="name" placeholder="Имя*" required>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="frm-group">
                                        <textarea name="msg" id="message" placeholder="Ваше сообщение" required></textarea>
                                        <div class="g-recaptcha" data-sitekey="6LfBGLEUAAAAAINWJJhMKw3AQCIgNjrwsa-Pehz3"></div>
                                    </div>
                                </div>

                                <div class="col-md-12">


                                    <div class="frm-group">
                                        <button type="submit" class="submit-btn">Ответить</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>

                </div><!-- blog-details-wrapper end -->
                <div class="comment-area">
                    <h3 class="title">Кол-во комментариев: {{ comment|length }}</h3>
                    <ul class="comment-list">
                        {% if comment|length >= 1  %}
                        {% for i in 0..comment|length-1 %}
                        <li>


                            <div class="single-comment-wrap">
                                <div class="thumb">
                                    <img src="{{ asset('assets/images/blog/rp1.svg') }}" alt="comment-thumb">
                                </div>
                                <div class="content">
                                    <h6 class="name">{{ comment[i].userName }}</h6>
                                    <span class="reply-time">{{  (date().timestamp - comment[i].time ) // 3600}} час(а) назад</span>
{#                                    <a href="" class="reply"><i class="fa fa-reply"></i></a>#}
                                    <p>{{ comment[i].comment }}</p>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                        {% endif %}

                    </ul>
                </div><!-- comment-area end -->

            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="widget widget-search">
                        <form class="widget-search-form">
                            <input type="search" name="search" id="widget-search" placeholder="Поиск...">
                            <button class="widget-search-btn"><i class="fa fa-search"></i></button>
                        </form>
                    </div><!-- widget end -->
                    <div class="widget widget-categories">


                    <a href="https://ggbetpromo.com/l/5d3f9dbd28c43f10615dfc0a"><img src="https://ggbetpromo.com/upload_dynamics/1513329710c42bda9290ba1aa445d1.gif" class="betPromo" alt="betPromo"></a>




{#                        random posts#}
                    </div><!-- widget end -->
                    <div class="widget widget-most-view-post">
                        <h4 class="widget-title">Вам может быть интересно</h4>
                        {% for i in 0..random_content|length-1 %}
                        <ul class="small-post-list">
                            <li>
                                <div class="small-post-item">
                                    <div class="small-post-thumb">
                                        <img src="{{ asset(random_content[i].img) }}" alt="{{ seo.alt }}">
                                    </div>
                                    <div class="small-post-content">
                                        <h6><a href="{{ random_content[i].slug }}">{{ random_content[i].title }}</a></h6>
                                        <ul class="post-meta">
                                            <li><a href="{{ random_content[i].slug }}"><i class="fa fa-calendar"></i>{{ random_content[i].date|date("d/M/Y") }}</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </li><!-- small-post-item end -->

                        </ul>
                        {% endfor %}
                    </div><!-- widget end -->




                </div>
            </div>
        </div>
    </div>
</section>
<!-- blog-details-section end -->

{% include 'usual_template/footer.html.twig' %}